pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/Ankush-verma-Source/devops-project-parallel-test-execution-manager.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                bat 'mvn clean install'
            }
        }

        stage('Run Selenium Grid with Docker') {
            steps {
                bat 'docker compose -f infrastructure/docker/docker-compose.yml up --build'
            }
        }

    }
}