pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/Ankush-verma-Source/devops-project-parallel-test-execution-manager.git'
            }
        }

        stage('Start Selenium Grid') {
            steps {
                bat 'docker compose -f infrastructure/docker/docker-compose.yml up -d'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn clean test'
            }
        }

        stage('Stop Selenium Grid') {
            steps {
                bat 'docker compose -f infrastructure/docker/docker-compose.yml down'
            }
        }

    }
}