pipeline {
    agent any

    stages {

        stage('Start Selenium Grid') {
            steps {
                bat 'docker compose -f infrastructure/docker/docker-compose.yml up -d'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn clean test'
            }
        }

        stage('Stop Selenium Grid') {
            steps {
                bat 'docker compose -f infrastructure/docker/docker-compose.yml down'
            }
        }

    }
}